Bug fix for migration of disjunction clauses
aws-cloudformation/cloudformation-guard pull request #148
Opened 2021-05-24 18:46 UTC by gandhek

*Issue #, if available:*
https://github.com/aws-cloudformation/cloudformation-guard/issues/135

*Description of changes:*

Incorrect migration of |OR| clauses from 1.0 => 2.0

Consider the template below
```
{
    "Resources": {
        "NewVolume" : {
            "Type" : "AWS::EC2::Volume",
            "Properties" : {
                "Size" : 100,
                "Encrypted": true,
                "AvailabilityZone" : "us-west-2b"
            }
        },
        "NewVolume2" : {
            "Type" : "AWS::EC2::Volume",
            "Properties" : {
                "Size" : 50,
                "Encrypted": true,
                "AvailabilityZone" : "us-west-2c"
            }
        }
    }
}
```

Guard 1.0 Rule:

```
let encryption_flag = true

AWS::EC2::Volume Encrypted == %encryption_flag
AWS::EC2::Volume Size == 100 |OR| AWS::EC2::Volume Size == 50
```

When running the rule against the example template using Guard 1.0, the result is "PASS"

Using the migrate functionality of Guard 2.0, the below rule is generated:

```
let aws_ec2_volume = Resources.*[ Type == "AWS::EC2::Volume" ]
        let encryption_flag = true

    %aws_ec2_volume.Properties.Encrypted == %encryption_flag
    %aws_ec2_volume.Properties.Size == 100 or %aws_ec2_volume.Properties.Size == 50
```
When running the migrated rule against the example template using Guard 2.0, the result is "FAIL" as the generated rule checks for ALL ec2 volume property size == 100 or ALL ec2 volume property size == 50 as opposed to ec2 property size of any == 100 or 50.

The PR fixes this for basic rules.

With this PR, the following rule is generated instead

```
rule migrated_rules {
	let aws_ec2_volume = Resources.*[ Type == "aws_ec2_volume" ]
		let encryption_flag = true
	%aws_ec2_volume.Properties.Encrypted == "%encryption_flag"
	%aws_ec2_volume {
		Properties.Size == 100 or Properties.Size == 50
	}
}

```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-05-27 01:51 UTC, dchakrav-github requested changes

2021-05-27 01:51 UTC, dchakrav-github commented on guard/src/migrate/parser.rs
> +                        Rule::Conditional(conditional) => {},
This should never occur based on the code above from 176 - 181. Just use the `if-let` form for these use cases, like `if let Rule::Basic(basic) = rule {...}`

2021-05-27 01:51 UTC, dchakrav-github commented on guard/src/migrate/parser_tests.rs
> +    let expected_rule_str = "\tlet encryption_flag = true\n%aws_ec2_volume.Properties.Encrypted == \"%encryption_flag\"\n%aws_ec2_volume {\n\t\tProperties.Size == 100 or Properties.Size == 50\n\t}";
See above comment, this must not be the form for `"%encryption_flag"`. With the quotes, it is string not variable access

2021-05-28 00:05 UTC, gandhek commented on guard/src/migrate/parser.rs
> +#[derive(Ord, Eq, PartialEq, PartialOrd, Debug, Clone, Hash)]
Having a TypeName and a custom display for it seems more consistent with the other constructs than having to do this every time we print.

2021-05-28 00:07 UTC, gandhek commented on guard/src/migrate/parser.rs
> +        let mut property_to_rules = HashMap::new();
Agreed, incorporated changes to ensure that Display does only writing

2021-05-28 02:24 UTC, dchakrav-github requested changes

2021-05-28 02:24 UTC, dchakrav-github commented on guard/src/migrate/parser.rs
> +        writeln!(f, "when %{}[ {} ] not EMPTY {{", self.type_name, self.when_condition);
If i understand the change right, you already have an external `%aws_ec2_volume { ... }` block. Inside the block `this` already refers each `AWS::EC2::Volume`, does this `when` check need the filter part? It seems like we will generate

```
      %aws_ec2_volume {
            %aws_ec2_volume[ Properties.Size > 500 ] NOT EMPTY {
                  %aws_ec2_volume[ Size > 500 ].Encrypted == false
            }
      }
```

We should just generate 
```
      %aws_ec2_volume {
             when Properties.Size > 500 {
                     Properties.Encrypted == false
             }
      }
```
Easier to comprehend as well.

2021-05-28 02:24 UTC, dchakrav-github commented on guard/src/commands/migrate_tests.rs
> +}
Please add tests for Conditional Rules (CR), rule with `OR`s of CR, rule with `OR`s with Conditional Rule and a Basic rule combination.

2021-05-28 02:24 UTC, dchakrav-github commented on guard/src/migrate/parser.rs
> +    delimited(space0, alt((
Please add an explanation on why this change was needed for the next set of maintainers. It is hard to understand why this change was made without the context surrounding this

2021-05-28 02:24 UTC, dchakrav-github commented on guard/src/migrate/parser_tests.rs
> +fn test_disjunction_basic_clauses() {
Please add tests for Conditional Rules and disjunction combinations across them as well.

2021-06-01 22:25 UTC, dchakrav-github requested changes

2021-06-01 22:25 UTC, dchakrav-github commented on guard/src/commands/migrate_tests.rs
> +    assert_eq!(result, expected_rule);
Comparing strings makes it very difficult to maintain. Create a `RulesFile` object from both migrated and expected strings and compares these objects

2021-06-01 22:25 UTC, dchakrav-github commented on guard/src/commands/migrate_tests.rs
> +    rules_file(span)?;
same comment as below parse both strings and compare the parsed objects

2021-06-01 22:25 UTC, dchakrav-github commented on guard/src/migrate/parser.rs
> +    delimited(space0, alt((
I get that gist from the change made in the code :). Elaborate on the context for 
1. Why was stripping white spaces needed? 
2. What was the error/consequence when this wasn't done?

2021-06-02 19:22 UTC, dchakrav-github approved these changes

2021-06-03 19:11 UTC, priyap286 approved these changes

2021-06-03 21:59 UTC, merged