fix: Added logic for evaluation of boolean values for is_empty
aws-cloudformation/cloudformation-guard pull request #269
Opened 2022-09-01 04:21 UTC by akshayrane

*Issue #, if available:*
#266 

*Description of changes:*
Added logic for evaluation of `is_empty` on top of a boolean value

---
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-09-01 15:06 UTC, razcloud approved these changes

2022-09-02 16:21 UTC, dchakrav-github requested changes

2022-09-02 16:21 UTC, dchakrav-github commented on guard/src/rules/eval.rs
> +                PathAwareValue::Bool((_, boolean)) => (*boolean).to_string().is_empty(),
What is the use case here? There is no `is_empty` operation on booleans.

2022-09-02 20:22 UTC, dchakrav-github approved these changes

2022-09-02 21:53 UTC, merged