fix rulegen invalid parameter
aws-cloudformation/cloudformation-guard pull request #453
Opened 2024-02-08 12:44 UTC by sejimhp

*Description of changes:*
Fixed a wrong parameter in the README of rulegen.

---
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-02-08 19:12 UTC, joshfried-aws approved these changes

2024-02-08 20:09 UTC, joshfried-aws requested changes
hi @sejimhp thank you for submitting this pr, please rebase for latest changes so the CI passes.

2024-02-09 07:03 UTC, sejimhp commented
@joshfried-aws Thanks for the review. I rebased this branch with the latest main.

2024-02-09 15:12 UTC, joshfried-aws approved these changes

2024-02-09 15:13 UTC, dannyvassallo approved these changes

2024-02-09 15:49 UTC, merged