[Enhancement] Writer error handling
aws-cloudformation/cloudformation-guard pull request #496
Opened 2024-04-12 17:46 UTC by dannyvassallo

*Issue #, if available:* N/A

*Description of changes:*

Update the writer to better handle errors rather than panic when used as a library.

---
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-04-12 19:23 UTC, joshfried-aws requested changes

2024-04-12 19:23 UTC, joshfried-aws commented on guard-examples/library/src/main.rs
> +            panic!("Error: {}", err);
we shouldn't be panicking here, we need to return an error

2024-04-12 19:23 UTC, joshfried-aws commented on guard/src/rules/errors.rs
> +    IncompatibleWriteError(String),
writer*

2024-04-12 19:23 UTC, joshfried-aws commented on guard/src/utils/writer.rs
> +            WriteBuffer::Stderr(..) => Err(Error::InternalError(IncompatibleWriteError(
same

2024-04-12 19:23 UTC, joshfried-aws commented on guard/src/utils/writer.rs
> +            WriteBuffer::Stdout(..) => Err(Error::InternalError(IncompatibleWriteError(
similar comment to previous function about needing a new error to better represent this

2024-04-12 19:23 UTC, joshfried-aws commented on guard/src/utils/writer.rs
> +                "Unable to strip ANSI escapes from stderr buffer.".to_string(),
same

2024-04-12 19:23 UTC, joshfried-aws commented on guard/src/utils/writer.rs
> +    fn into_string(self) -> crate::rules::Result<String> {
same comment as i left about the errors in the 2 previous functions.

2024-04-12 19:23 UTC, joshfried-aws commented on guard/src/utils/writer.rs
> +            WriteBuffer::Vec(vec) => match String::from_utf8(vec) {
Nit: we can just use the `?` operator here

2024-04-12 19:23 UTC, joshfried-aws commented on guard/src/utils/writer.rs
> +                match String::from_utf8(stripped?) {
Nit: We can also dont need to match on the `String::from_utf8` function call, we can just use the `?` operator

2024-04-12 19:24 UTC, joshfried-aws commented on guard-examples/library/src/main.rs
> +            panic!("Error: {}", err);
Whoops, misread the example.

2024-04-15 13:46 UTC, joshfried-aws commented on guard/src/utils/writer.rs
> +                String::from_utf8(stripped)
Are you unable to just use the `?` operator here and let thiserror work its magic?

2024-04-15 14:26 UTC, joshfried-aws approved these changes

2024-04-15 18:18 UTC, minhphuong98 approved these changes

2024-04-15 19:10 UTC, merged